Traceback (most recent call last):
  File "/Users/chao/anaconda3/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/chao/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chao/anaconda3/lib/python3.11/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chao/anaconda3/lib/python3.11/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chao/anaconda3/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/chao/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/chao/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/chao/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
### One reason why we use "numpy" instead of "math" in Deep Learning ###

x = [1, 2, 3] # x becomes a python list object
basic_sigmoid(x) # you will see this give an error when you run it, because x is a vector.
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[5], line 4[0m
[1;32m      1[0m [38;5;66;03m### One reason why we use "numpy" instead of "math" in Deep Learning ###[39;00m
[1;32m      3[0m x [38;5;241m=[39m [[38;5;241m1[39m, [38;5;241m2[39m, [38;5;241m3[39m] [38;5;66;03m# x becomes a python list object[39;00m
[0;32m----> 4[0m basic_sigmoid(x)

Cell [0;32mIn[3], line 19[0m, in [0;36mbasic_sigmoid[0;34m(x)[0m
[1;32m      7[0m [38;5;250m[39m[38;5;124;03m"""[39;00m
[1;32m      8[0m [38;5;124;03mCompute sigmoid of x.[39;00m
[1;32m      9[0m 
[0;32m   (...)[0m
[1;32m     14[0m [38;5;124;03ms -- sigmoid(x)[39;00m
[1;32m     15[0m [38;5;124;03m"""[39;00m
[1;32m     16[0m [38;5;66;03m# (â‰ˆ 1 line of code)[39;00m
[1;32m     17[0m [38;5;66;03m# s = [39;00m
[1;32m     18[0m [38;5;66;03m# YOUR CODE STARTS HERE[39;00m
[0;32m---> 19[0m s [38;5;241m=[39m [38;5;241m1[39m [38;5;241m/[39m ([38;5;241m1[39m [38;5;241m+[39m math[38;5;241m.[39mexp([38;5;241m-[39mx))
[1;32m     21[0m [38;5;66;03m# YOUR CODE ENDS HERE[39;00m
[1;32m     23[0m [38;5;28;01mreturn[39;00m s

[0;31mTypeError[0m: bad operand type for unary -: 'list'
TypeError: bad operand type for unary -: 'list'

